-- Table: public.employee

-- DROP TABLE public.employee;

CREATE TABLE public.employee
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    login character varying(20) COLLATE pg_catalog."default",
    password character varying(60) COLLATE pg_catalog."default",
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    birthdate date,
    phone character varying(20) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    address character varying(100) COLLATE pg_catalog."default",
    rating real,
    review_count integer,
    about character varying(200) COLLATE pg_catalog."default",
    experience integer,
    animal_id bigint,
    prices_id bigint,
    rating_id bigint,
    CONSTRAINT employee_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.employee
    OWNER to postgres;